apiVersion: v1
kind: Service
metadata:
  name: {{ include "zuul.fullname" . }}
  labels:
    {{- include "zuul.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.service.targetport }}
      nodePort: {{ .Values.service.nodeport }}
  selector:
    {{- include "zuul.selectorLabels" . | nindent 4 }}
